---
version: '3.9'
name: mautrix-discord
# Use with: docker --context kraud.grass1797 compose up -d
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ir9Aeciehaeng4iqu5niQu7ohkooK7EeGhaiyoabahkeiquiya0euxie1zeecoof
    volumes:
      - postgres:/var/lib/postgresql/data
  mautrix-discord:
    container_name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:latest
    restart: unless-stopped
    depends_on:
      - postgres
    labels:
      kr.ingress.29334: https://dd.*
    ports:
      - "29334:29334"
    volumes:
      - mautrix-discord:/data

volumes:
  postgres:
    driver_opts:
      size: 10G
  mautrix-discord:
    driver_opts:
      size: 100M
