---
version: '3.9'
name: mautrix-whatsapp
# Use with: docker --context kraud.mountain9185 compose up -d
services:
  mautrix-whatsapp:
    container_name: mautrix-whatsapp
    image: wa:latest
    restart: unless-stopped
    labels:
      - kr.res.cpu=4Ghz
      - kr.res.mem=4G
      - kr.ingress.29318=https://wa.*
    ports:
      - "29318:29318"
    stdin_open: true
    tty: true
    volumes:
      - mautrix-whatsapp:/data

volumes:
  mautrix-whatsapp:
